name: cityflows-model-docker
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - azure-storage-blob=12.8.1
  - confuse=1.1.0
  - geopandas=0.9.0
  - gurobi=9.1.2
  - kafka-python=2.0.2
  - numpy=1.20.3
  - osqp=0.6.2
  - pandas=1.2.4
  - pip=21.1.2
  - progress=1.5
  - psutil=5.8.0
  - python=3.7
  - scipy=1.6.3
  - shapely=1.7.1
  - typing=3.7.4.3
  - pip:
    - geodaisy==0.1.1
