name: cityflows-model
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - autopep8=1.6.0
  - azure-core=1.14.0
  - azure-storage-blob=12.8.1
  - confuse=1.5.0
  - folium=0.12.0
  - fuzzywuzzy=0.18.0
  - geopandas=0.9.0
  - gurobi=9.1.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - notebook=6.4.0
  - numpy=1.20.3
  - openpyxl=3.0.9
  - osqp=0.6.2
  - pandas=1.3.5
  - pip=21.1.2
  - polycircles=0.3.7
  - progress=1.5
  - psutil=5.8.0
  - pyproj=3.1.0
  - python=3.7
  - requests=2.25.1
  - scipy=1.6.3
  - seaborn=0.11.1
  - shapely=1.7.1
  - ipywidgets=7.6.5
  - pip:
    - geodaisy==0.1.1
    - geovoronoi==0.4.0
    - keplergl==0.3.2
