apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  config.yaml: |
    {{- .Values.configmap | toYaml | nindent 4 }}